### PR TITLE
Bug/weighted sampling reader

### PR DESCRIPTION
**Pull request by gueguenster**
- _petastorm.pytorch.DataLoader_ expects the field _is_batched_reader_ in the reader. _WeightedSamplingReader_ does not have this field. It seems to be replaced by the property: _batched_output_.

- _petastorm.pytorch.DataLoader_ expects the functions _stop()_ and _join()_ from the reader. _WeightedSamplingReader_ does not have these functions. This PR adds these functions.

### CODE REVIEW

**Review by selitvin — APPROVED** [review]
Thanks Lionel!

**Comment by selitvin** [comment]
@gueguenster , can you please sign the CLA?

**Comment by selitvin** [comment]
@gueguenster : seems that the problem is not CLA but that we have Robert appears as author of one of the unrelated comments in the commit stack. Can you please rebase and remove Robert's commits + push-force?

**Comment by gueguenster** [comment]
@selitvin , thanks I look in fixing that.

**Comment by gueguenster** [comment]
I had difficulty removing the commits.

**Pull request closed without merging**
