### PR TITLE
handle names like [path]/part/

### PR DESCRIPTION
**Pull request by xiaohanhuang**
gcsfs returns name as [path]/part/, and in this case. Following code will set directories to list of empty strings.
```
        directories = sorted([posixpath.split(x)[1]
                              for x in directories])
```

### CODE REVIEW

**Comment by xiaohanhuang** [comment]
@selitvin Is the test coverage required? This is very minor and safe change. If not required, could you merge this change? Thanks

**Comment by selitvin** [comment]
Yep. Can merge.

**Comment by xiaohanhuang** [comment]
> Yep. Can merge.

A reminder. Thanks

**Comment by xiaohanhuang** [comment]
> Yep. Can merge.

@selitvin Could you merge this? It is a minor fix but it is blocking and hard to find work around. Thanks

**Comment by selitvin** [comment]
Sure. Please ping me on slack if you see I am not responding. Sometimes some git notifications slip through holes in my inbox.

**Pull request merged**
