### PR TITLE
Parameterize factory methods with s3 configs

### PR DESCRIPTION
**Pull request by dmcguire81**
Implements #593

### CODE REVIEW

**Review by selitvin — APPROVED** [review]
Please add a line to `docs/release-notes.rst`. Otherwise, I think this is good. Let me know if we you would like me to land.

**Comment by dmcguire81** [comment]
Updated. This can be merged.

**Comment by dmcguire81** [comment]
@selitvin how do I make the erroneous Codecov errors go away?

**Comment by selitvin** [comment]
I think it's about codecov configuration file. Did not have time to fix this - I am just looking at the actual numbers and if they make sense, then force land it.

**Pull request merged**
