### PR TITLE
Tests: fix the unit test of batched dataloader with in-memory cache

### LINKED ISSUE #642: Failure in "test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache"
The parameter `shuffling_queue_capacity` is not used in the unit test. That means it is always `0`.

https://github.com/uber/petastorm/blob/15b35798d6140efe90f8467072dd55d12a8f79c1/petastorm/tests/test_pytorch_dataloader.py#L230

However, if I added `shuffling_queue_capacity` into `extra_loader_params`, test with `shuffling_queue_capacity=20` are all 
 failing.
https://github.com/uber/petastorm/blob/15b35798d6140efe90f8467072dd55d12a8f79c1/petastorm/tests/test_pytorch_dataloader.py#L238

```
(petastorm_venv3.7) root@4d7bc42e93c2:/petastorm/petastorm/tests# pytest -v test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache
==================================================================== test session starts ====================================================================
platform linux -- Python 3.7.9, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /petastorm_venv3.7/bin/python3.7
cachedir: .pytest_cache
rootdir: /petastorm
plugins: forked-1.3.0, timeout-1.4.2, cov-2.11.1, logger-0.5.1
collected 16 items

test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[1-make_batch_reader-20] FAILED                                              [  6%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[1-make_batch_reader-0] PASSED                                               [ 12%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[1-make_reader-20] FAILED                                                    [ 18%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[1-make_reader-0] PASSED                                                     [ 25%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[2-make_batch_reader-20] FAILED                                              [ 31%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[2-make_batch_reader-0] PASSED                                               [ 37%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[2-make_reader-20] FAILED                                                    [ 43%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[2-make_reader-0] PASSED                                                     [ 50%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[3-make_batch_reader-20] FAILED                                              [ 56%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[3-make_batch_reader-0] PASSED                                               [ 62%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[3-make_reader-20] FAILED                                                    [ 68%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[3-make_reader-0] PASSED                                                     [ 75%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[None-make_batch_reader-20] FAILED                                           [ 81%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[None-make_batch_reader-0] PASSED                                            [ 87%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[None-make_reader-20] FAILED                                                 [ 93%]
test_pytorch_dataloader.py::test_batched_data_loader_with_in_memory_cache[None-make_reader-0] PASSED                                                  [100%]
```

Is this a known issue or we just missed that?

@abditag2 @selitvin @tgaddair

### PR DESCRIPTION
**Pull request by chongxiaoc**
Also add comments of setting shuffling_queue_capacity correctly when
enablding in memory cache.

Fix #642

### CODE REVIEW

**Review by selitvin — COMMENTED** [review]
Can  you please clarify - this is a PR into master. Is master currently broken?

**Comment by chongxiaoc** [comment]
> Can you please clarify - this is a PR into master. Is master currently broken?

@selitvin This is a missed testing case in master. And if enable it, it will fail.

This PR just adds the missed tests and fixes it.

**Review by tgaddair — APPROVED** [review]

**Comment by tgaddair** [comment]
@selitvin, should we ignore the failing Docker tests?

**Comment by selitvin** [comment]
Yep. Ok to ignore docker.

**Comment by chongxiaoc** [comment]
@selitvin Can we merge this one?

**Pull request merged**
